#!/bin/bash
#
# vim: set tabstop=4 shiftwidth=4 expandtab autoindent:
#

help=$(cat << 'EOF'

Change parent to a specific commit.

Usage:

    git-chparent.sh [-b <branch>]  <target revision> <parent revision>... 

Options:

    -b Branch to be filtered on
EOF
)

# ============================================================================
all=True
while getopts :b:h opt
do
    case $opt in
    'b')    branch=$OPTARG; all=FALSE
            ;;
    'h')    echo "$help"
            exit 0
            ;;
      ?)    echo "invalid arg"
            echo "$help"
            exit 1
            ;;
    esac
done

# ============================================================================

grafts="$(git rev-parse --show-toplevel)/.git/info/grafts" \
	|| (echo "Could not find Git repository"; exit 1)

shift $((OPTIND - 1))
target_commit=$(git rev-parse $1)
shift 

parent_commits=`for parent_commit in $*; do echo -n " $(git rev-parse $parent_commit)"; done`

echo "CHANGING PARENTS OF $target_commit TO $parent_commits"

echo "$target_commit$parent_commits" > $grafts

# ============================================================================
[ -n "$all" ]    && range='-- --all' || range='HEAD'
[ -n "$branch" ] && range="$branch"

# ============================================================================
git filter-branch \
    --force \
    $range

git gc

rm $grafts
