#!/usr/bin/env ruby

def source()
    if ENV['H2_SOURCE']
        return ENV['H2_SOURCE']
    else
        return "~/.h2"
    end
end

def editor()
    if ENV['H2_EDITOR']
        return ENV['H2_EDITOR']
    elsif ENV['EDITOR']
        return ENV['EDITOR']
    else
        return 'vim'
    end
end

# ============================================================================
topics = {}
current_element = []

def colorize(text, color_code)
  "\033#{color_code}#{text}\033[0m"
end

def red(text)
    colorize(text, "[31m")
end

def green(text)
    colorize(text, "[32m")
end

# ============================================================================

def check_action
    if $*[0] == "--edit"
        exec("#{editor()} #{source()}")
    elsif $*[0] == "--hack"
        sourceFile = `readlink #{__FILE__} || echo #{__FILE__}`
        exec("#{editor()} #{sourceFile}")
    end
end


def print_help
    puts <<EOF
h2 usage: h2 [command|searchstring]
    command: --edit 
             --hack 
    
Examples:   h2 bash
EOF
    exit 0
end

# ============================================================================

if __FILE__ == $0

    if $*.size == 1
        check_action()
    elsif $*.size == 0
        print_help()
    end
    
    File.readlines(source()).each { |line|
        if line =~/^\-\ .*/
            current_element = []
            topics[line] = current_element 
        else
            current_element.push line
        end
    }
    # find the matching groups -----------------------------------------------
    output = ''
    topics.each_pair { |k,v|
        matches = true
        $*.each {|search|
            if not k.downcase.match search.downcase and
               not v.join.downcase.match search.downcase
                 matches = false
                 break
            end
        }
        if matches
            # the header in green
            output += green(k.strip) + "\n"
            # strip the first indentation of each body line
            output += v.collect{|l| l.gsub(/^(\t|    )/, '')}.to_s 
        end
    }
    # colorize the matches ---------------------------------------------------
    output = output.split("\n")
    $*.each { |search|
        output.length.times { |i|
            # if its the green header line, add a green continue color
            if output[i].start_with? "\033[31m" or output[i][1]==91
                output[i].gsub!(search, "\033[31m" + '\0' + "\033[32m")
            else
                output[i].gsub!(search, "\033[31m" + '\0' + "\033[0m")
            end
        }
    }
    puts output
end 
