#!/bin/bash

TM_FILEPATH=$1
TM_FILEPATH=`basename ${TM_FILEPATH}`
# temporary file for the output xml
tmp_xml="/tmp/${TM_FILEPATH%.*}.xml"

# final pdf destination
dest=${TM_FILEPATH%.*}.pdf

# HTML header
cat > $tmp_xml <<EOD
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <title></title>
   </head>
   <body>
EOD

# this is the body of the document
markdown $TM_FILEPATH >> $tmp_xml

# close up the tags
cat >> $tmp_xml <<EOD
</body>
</html>
EOD

# convert temp xml to pdf
prince $tmp_xml $dest

# remove temp files
rm $tmp_xml
